M48
; DRILL file {KiCad 8.0.1} date 2024-04-27T09:51:49+0930
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-27T09:51:49+09:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.397
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X148.643Y-92.987
T2
X133.5Y-114.5
X164.5Y-91.5
M30
