name: Generate Interactive BOM

on:
  workflow_dispatch:  # Only runs when manually triggered

jobs:
  generate-ibom:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for commits

      - name: 🔧 Set up KiCad and InteractiveHtmlBom
        run: |
          sudo add-apt-repository -y ppa:kicad/kicad-9.0-releases
          sudo apt update
          sudo apt install -y kicad
          pip install InteractiveHtmlBom

      - name: 🛠 Generate Interactive BOM
        run: |
          generate_interactive_bom hardware/hawk.kicad_pcb
          mv hardware/hawk_ibom.html .kitspace/hawk_ibom.html

      - name: 📤 Commit and Push Updated BOM
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .kitspace/hawk_ibom.html
          git commit -m "🔄 Update Interactive BOM"
          git checkout -B "test"
          git push test -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
